import classNames from 'classnames';
import PropTypes from 'prop-types';
import React, {useCallback, useState} from 'react';
import {defineMessages, FormattedMessage, useIntl} from 'react-intl';

import ToolCallRow, {TOOL_CALL_STATUS} from './tool-call-row.jsx';

import styles from './message-bubble.css';

const MESSAGE_ROLES = ['user', 'assistant', 'system'];

/** Matches the inline spans this renderer understands: code spans and bold runs. */
const INLINE_PATTERN = /(`[^`\n]+`|\*\*[^*]+\*\*)/;

const messages = defineMessages({
    reasoning: {
        id: 'gui.aiAssist.reasoning',
        defaultMessage: 'Reasoning',
        description: 'Label for the collapsible section holding the reasoning a model reported before answering'
    },
    roleAssistant: {
        id: 'gui.aiAssist.roleAssistant',
        defaultMessage: 'Assistant',
        description: 'Label identifying a message written by the AI assistant'
    },
    roleSystem: {
        id: 'gui.aiAssist.roleSystem',
        defaultMessage: 'System',
        description: 'Label identifying a message generated by the editor rather than a person or the assistant'
    },
    roleUser: {
        id: 'gui.aiAssist.roleUser',
        defaultMessage: 'You',
        description: 'Label identifying a message written by the person using the editor'
    }
});

const roleMessages = {
    assistant: messages.roleAssistant,
    system: messages.roleSystem,
    user: messages.roleUser
};

/**
 * Split one run of text into React children, honouring code spans and bold runs.
 * @param {string} text the text to render
 * @param {string} keyPrefix prefix making the generated keys unique within the message
 * @returns {Array} React children
 */
const renderInline = (text, keyPrefix) => text.split(INLINE_PATTERN).map((part, index) => {
    const key = `${keyPrefix}-${index}`;
    if (part.length > 2 && part.startsWith('`') && part.endsWith('`')) {
        return (
            <code
                className={styles.inlineCode}
                key={key}
            >{part.slice(1, -1)}</code>
        );
    }
    if (part.length > 4 && part.startsWith('**') && part.endsWith('**')) {
        return <strong key={key}>{part.slice(2, -2)}</strong>;
    }
    return part;
});

/**
 * Split text into paragraph and fenced-code blocks.
 *
 * A fence that never closes is the normal shape of a partially streamed reply,
 * so its contents are emitted as a code block rather than as prose.
 * @param {string} text the message content
 * @returns {Array<{type: string, text: string}>} the blocks, in order
 */
const parseBlocks = text => {
    const blocks = [];
    let paragraph = [];
    let code = null;

    const flushParagraph = () => {
        const joined = paragraph.join('\n').replace(/^\n+|\n+$/g, '');
        paragraph = [];
        if (joined) blocks.push({type: 'paragraph', text: joined});
    };

    for (const line of text.split('\n')) {
        if (line.startsWith('```')) {
            if (code) {
                blocks.push({type: 'code', text: code.join('\n')});
                code = null;
            } else {
                flushParagraph();
                code = [];
            }
        } else if (code) {
            code.push(line);
        } else {
            paragraph.push(line);
        }
    }

    if (code) blocks.push({type: 'code', text: code.join('\n')});
    flushParagraph();

    return blocks;
};

/**
 * Render a deliberately small subset of Markdown: bold runs, code spans and
 * fenced code blocks. Anything else is shown verbatim.
 * @param {string} text the message content
 * @returns {Array} React children
 */
const renderMarkdown = text => parseBlocks(text).map((block, blockIndex) => {
    if (block.type === 'code') {
        return (
            <pre
                className={styles.codeBlock}
                key={`block-${blockIndex}`}
            ><code>{block.text}</code></pre>
        );
    }
    return block.text.split(/\n{2,}/).map((paragraph, paragraphIndex) => (
        <p
            className={styles.paragraph}
            key={`block-${blockIndex}-${paragraphIndex}`}
        >{renderInline(paragraph, `block-${blockIndex}-${paragraphIndex}`)}</p>
    ));
});

const MessageBubble = props => {
    const {isStreaming, message} = props;
    const intl = useIntl();
    const [reasoningExpanded, setReasoningExpanded] = useState(false);

    const handleToggleReasoning = useCallback(() => {
        setReasoningExpanded(expanded => !expanded);
    }, []);

    const reasoningId = `ai-assist-reasoning-${message.id}`;

    return (
        <li className={classNames(styles.bubble, styles[message.role], {[styles.hasError]: !!message.error})}>
            <span className={styles.role}>{intl.formatMessage(roleMessages[message.role])}</span>

            {message.reasoning ? (
                <div className={styles.reasoning}>
                    <button
                        aria-controls={reasoningId}
                        aria-expanded={reasoningExpanded}
                        className={styles.reasoningToggle}
                        type="button"
                        onClick={handleToggleReasoning}
                    >
                        <span className={classNames(styles.caret, {[styles.caretOpen]: reasoningExpanded})} />
                        {intl.formatMessage(messages.reasoning)}
                    </button>
                    {reasoningExpanded ? (
                        <div
                            className={styles.reasoningBody}
                            id={reasoningId}
                        >{message.reasoning}</div>
                    ) : null}
                </div>
            ) : null}

            {message.toolCalls && message.toolCalls.length > 0 ? (
                <ul className={styles.toolCalls}>
                    {message.toolCalls.map(toolCall => (
                        <ToolCallRow
                            durationMs={toolCall.durationMs}
                            error={toolCall.error}
                            key={toolCall.id}
                            name={toolCall.name}
                            status={toolCall.status}
                        />
                    ))}
                </ul>
            ) : null}

            {message.attachments && message.attachments.length > 0 ? (
                <ul className={styles.attachments}>
                    {message.attachments.map(attachment => (
                        <li
                            className={styles.attachment}
                            key={attachment.name}
                        >
                            {attachment.mimeType.startsWith('image/') ? (
                                <img
                                    alt={attachment.name}
                                    className={styles.attachmentThumb}
                                    src={attachment.dataUrl}
                                />
                            ) : null}
                            <span className={styles.attachmentName}>{attachment.name}</span>
                        </li>
                    ))}
                </ul>
            ) : null}

            <div className={styles.content}>
                {message.role === 'assistant' ? renderMarkdown(message.content) : message.content}
                {isStreaming ? (
                    <span
                        className={styles.typingCaret}
                        data-testid="streaming-caret"
                    />
                ) : null}
            </div>

            {message.error ? (
                <div
                    className={styles.error}
                    role="alert"
                >
                    <FormattedMessage
                        defaultMessage="Something went wrong: {error}"
                        description="Error shown on an assistant message that could not be completed"
                        id="gui.aiAssist.messageError"
                        values={{error: message.error}}
                    />
                </div>
            ) : null}
        </li>
    );
};

const messageShape = PropTypes.shape({
    attachments: PropTypes.arrayOf(PropTypes.shape({
        dataUrl: PropTypes.string.isRequired,
        mimeType: PropTypes.string.isRequired,
        name: PropTypes.string.isRequired
    })),
    content: PropTypes.string.isRequired,
    createdAt: PropTypes.number.isRequired,
    error: PropTypes.string,
    id: PropTypes.string.isRequired,
    reasoning: PropTypes.string,
    role: PropTypes.oneOf(MESSAGE_ROLES).isRequired,
    toolCalls: PropTypes.arrayOf(PropTypes.shape({
        durationMs: PropTypes.number,
        error: PropTypes.string,
        id: PropTypes.string.isRequired,
        name: PropTypes.string.isRequired,
        status: PropTypes.oneOf(TOOL_CALL_STATUS).isRequired
    }))
});

MessageBubble.propTypes = {
    isStreaming: PropTypes.bool,
    message: messageShape.isRequired
};

MessageBubble.defaultProps = {
    isStreaming: false
};

export {
    MessageBubble as default,
    MESSAGE_ROLES,
    messageShape
};
